updated stable
tkitCognits/CMI-express-sendgrid pull request #2
Opened 2021-11-22 21:33 UTC by cmontiel12345

2021-11-22 22:42 UTC, llocon requested changes

2021-11-22 22:42 UTC, llocon commented on index.js
> +    }).then(response => response.json()).then(data => obj = data);
si estas usando await, no deberías usar el método Then() porque el resultado dentro de then debería contenerse dentro de response en la linea 87, estas haciendo un paso de mas! 

Para replicarlo seria como 

```
const response = await fetch("...")
obj = await response.json();
```

2021-11-23 04:21 UTC, cmontiel12345 commented on index.js
> +    }).then(response => response.json()).then(data => obj = data);
@llocon Lo puse de esa forma porque estaba teniendo errores de indefinición

2021-11-23 04:53 UTC, llocon commented on index.js
> +    }).then(response => response.json()).then(data => obj = data);
En ese caso @cmontiel12345 usa la forma del promise chain sin el await. De lo contrario estarías mezclando conceptos

2021-11-23 05:01 UTC, cmontiel12345 commented on index.js
> +    }).then(response => response.json()).then(data => obj = data);
@llocon  He corregido el cambio, puedes revisarlo?

2021-11-23 15:04 UTC, merged